### ISSUE TITLE
Solcast Error gathering rooftop sites data

### ISSUE THREAD

**Issue by Dehumanizer77** [oziee/ha-solcast-solar#307]
### The problem

I started getting this error today:
`2024-05-29 10:53:15.016 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Exception error: Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/solcastapi.py", line 144, in sites_data
    raise Exception(f"SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.")
Exception: SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.
`
I am using the latest version of the integration, 4.0.22 and HA 2024.5.5

When I log in to my solcast account, everything seems to be working and their API status page also does not report any problems.

### What version of Solcast Integration has the issue?

v4.0.22

### What version of Home Assistant are you using?

core-2024.5.5

### Logs debug/info/error output

```txt
2024-05-29 10:53:15.016 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Exception error: Traceback (most recent call last):
  File "/config/custom_components/solcast_solar/solcastapi.py", line 144, in sites_data
    raise Exception(f"SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.")
Exception: SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.
```

**Comment by paulmthomas2** [comment]
Following along as my solcast doesn't seem to be updating today. I regenerated and reconfigured a new API key which hasn't made a difference. Currently everything showing as zero or "unavailable". I've polled the API but counter still showing nil etc.

**Comment by blade566** [comment]
I have the same message, i reinstall the component HACS to de other version, restart, try with de 4.0.22 and i have the same message

**Comment by wimdebruyn** [comment]
On v4.0.17, no problems.

**Comment by Ben00793** [comment]
On v4.0.22 same issue. no polling today. everthing is on 0.

**Comment by paulmthomas2** [comment]
Have tried all versions 4.0.18 - 4.0.22 - all with same result

**Comment by wimdebruyn** [comment]
Just noticed last successful poll was 6 hours ago, missing two polls in the
interim. Likely a problem at solcast.

**Comment by Christoffer-da** [comment]
I have the same exact issue. 
When polling today: 29-05-2024 at 4:27 UTC everything worked, polling again 6:33 I got the same error.

**Comment by timparker71** [comment]
I have the same issue today. Setting up a new account in Solcast, taking the API key and adding to Home Assistant integration the sensors return zero.
Unfortunately I also accidently reset the API key on an existing account that was working well in another instance of Solcast (much older version) within Home assistant. That is also now returning zero data. So I've broken two things!

**Comment by Ben00793** [comment]
it must be a fault on the solcast side

**Comment by rjdiver** [comment]
In my traces I did get this a couple of times;
Error: Solcast API did not return a json object. Returned None
It is now running through, but no updates and Solcast has only recognised 1 API call today. GivEnergy link to Solcast from the webportal has also broke.

**Comment by rjdiver** [comment]
Additional: Yesterday when I was having the problem, Regenerating the API key in Solcast fixed the issue, that no longer works today.

**Comment by hwb45** [comment]
I have the same issue. Solcast reporting their API IS OK

**Comment by niggles1973** [comment]
Same issue  File "/config/custom_components/solcast_solar/solcastapi.py", line 144, in sites_data
    raise Exception(f"SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.")
Exception: SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.
immediately after a restart

Ditto; have followed all the items like polling at on the hour but adding random 300 second amount - works perfectly until a reboot; than 0 for everything; and a last update time many years in the past.

**Comment by paulmthomas2** [comment]
Worth noting that on the solcast actual website, when i go to site detail i don't see anything in the graph-live and forecasts box, and if i try to download data from the APIby clicking the "download JSON" button, i get a "this page isn't working now" HTTP error 429, so it does probably suggest something their end

**Comment by ElmarJansen** [comment]
Same failiure since this morning, 0 results here😞

**Comment by jodewee** [comment]
looks like it's the solcast side. Neither csv or json downloads work also

**Comment by Stephens-ely** [comment]
Same here - Am sure it's a Solcast issue but notifying so I can get updates to the issue.

**Comment by catalinbordan** [comment]
Shall we send email to Solcast to notify them, because the status on their page it say that everything it is ok?

**Comment by Dehumanizer77** [comment]
I'd say we can wait for @oziee to confirm it's definitelly a solcast issue, but sending email to Solcast won't hurt anyway...

**Comment by catalinbordan** [comment]
I have just send one to them. I say that if we send more guys, the better will be.

**Comment by martinarva** [comment]
debug logs:
`2024-05-29 09:45:55.531 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Exception error: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/solcastapi.py", line 144, in sites_data
raise Exception(f"SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.")
Exception: SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.
2024-05-29 14:46:51.840 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Solcast.com http status Error 429 - Gathering rooftop sites data.
2024-05-29 14:46:51.844 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Exception error: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/solcastapi.py", line 144, in sites_data
raise Exception(f"SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.")
Exception: SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.
2024-05-29 14:52:18.771 DEBUG (MainThread) [custom_components.solcast_solar] Solcast Migrating from version 7
2024-05-29 14:52:18.771 DEBUG (MainThread) [custom_components.solcast_solar] Solcast Migration to version 7 successful
2024-05-29 14:52:18.772 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - trying to connect to - https://api.solcast.com.au/rooftop_sites?format=json&api_key=REDACTED
2024-05-29 14:52:18.927 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data code http_session returned data type is <class 'NoneType'>
2024-05-29 14:52:18.927 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data code http_session returned status 429
2024-05-29 14:52:18.927 WARNING (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Solcast.com http status Error 429 - Gathering rooftop sites data.
2024-05-29 14:52:18.929 ERROR (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data Exception error: Traceback (most recent call last):
File "/config/custom_components/solcast_solar/solcastapi.py", line 144, in sites_data
raise Exception(f"SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.")
Exception: SOLCAST - HTTP sites_data error: Solcast Error gathering rooftop sites data.
2024-05-29 14:52:18.929 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - getting API limit and usage from solcast
2024-05-29 14:52:19.622 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_usage returned data: {'daily_limit': 10, 'daily_limit_consumed': 4}
2024-05-29 14:52:19.622 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - load_saved_data site count is zero!
2024-05-29 14:52:19.623 INFO (MainThread) [custom_components.solcast_solar] Solcast Integration version number: v4.0.22
2024-05-29 14:52:19.624 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Finished fetching solcast_solar data in 0.000 seconds (success: True)
2024-05-29 14:52:19.659 INFO (MainThread) [custom_components.solcast_solar] SOLCAST - Solcast API data UTC times are converted to Europe/Tallinn`

**Comment by markwoodward86** [comment]
This seems to be a Solcast issue. When using postman to query any and all API endpoints i get

```
{
    "response_status": {
        "error_code": "Forbidden",
        "message": "User does not have active plan for forecast_rooftop_pv_power",
        "errors": []
    }
}
```

**Comment by Buggykiter** [comment]
Same problem here. Login to Solcast is possible, but "View Site detail" gives an empty page.
![Solcast error](https://github.com/oziee/ha-solcast-solar/assets/125905519/87da7f4c-fdad-4a24-8f2f-6f0af4a4857e)

**Comment by Dehumanizer77** [comment]
Also I will abuse this thread to ask if anyone sending the report to solcast could also ask if there is any option of paid subscription to raise the number of daily requests, because 10 (for newly created accounts like mine) is really low, especially when one requests counts as 2 when I have 2 strings. 
I was asking them but they said it's not possible to raise the limit and they don't have paid accounts for hobbyists. I suppose I could create a commercial account but the cost would be probably also "commercial" :-) They said they might reconsider in the future so if enough people ask, they might be willing to do something with it.

**Comment by djfanatix** [comment]
Its on Solcast side, I get an error 429, rate limited.
I am the dev of the Solcast Homey app, and there we have the same issues

**Comment by insipiens** [comment]
> Also I will abuse this thread to ask if anyone sending the report to solcast could also ask if there is any option of paid subscription to raise the number of daily requests, because 10 (for newly created accounts like mine) is really low, especially when one request counts as 2 when I have 2 strings. I was asking them but they said it's not possible to raise the limit and they don't have paid accounts for hobbyists. I suppose I could create a commercial account but the cost would be probably also "commercial" :-) They said they might reconsider in the future so if enough people ask, they might be willing to do something with it.



> Also I will abuse this thread to ask if anyone sending the report to solcast could also ask if there is any option of paid subscription to raise the number of daily requests, because 10 (for newly created accounts like mine) is really low, especially when one request counts as 2 when I have 2 strings. I was asking them but they said it's not possible to raise the limit and they don't have paid accounts for hobbyists. I suppose I could create a commercial account but the cost would be probably also "commercial" :-) They said they might reconsider in the future so if enough people ask, they might be willing to do something with it.

They probably don’t have a team & infrastructure that can handle lots of small customers’ issues unless they charge a price hobbyists would find prohibitive. Hence the free but take it or leave it status quo….

**Comment by Croft5** [comment]
My system failed to update any Solcast data early this morning (01:30 UK time) and is not updating now (18:27 UK time)

**Comment by philjohn** [comment]
> Also I will abuse this thread to ask if anyone sending the report to solcast could also ask if there is any option of paid subscription to raise the number of daily requests, because 10 (for newly created accounts like mine) is really low, especially when one request counts as 2 when I have 2 strings. I was asking them but they said it's not possible to raise the limit and they don't have paid accounts for hobbyists. I suppose I could create a commercial account but the cost would be probably also "commercial" :-) They said they might reconsider in the future so if enough people ask, they might be willing to do something with it.

I asked some time ago - they offered a 50% discount ... which would still have been £100 a month.

**Comment by heikone** [comment]
Also my installation is not working anymore since last night.
Let's wait and see if @oziee can provide a solution.

**Comment by markwoodward86** [comment]
> Also my installation is not working anymore since last night. Let's wait and see if @oziee can provide a solution.

I dont think that its the developer of this integration that needs to provide the solution, it looks like a Solcast issue per the comments above.

**Comment by maritzhome1** [comment]
Same for me also.

**Comment by viking2010** [comment]
Looks like it's back up and running again now.  The website is populating the graphs and the json is downloadable. 

As for the integration, you will need to reload it but it's started polling again now and bringing figures back.

**Comment by didi31** [comment]
The answer from Solcast:
Apologies for the issues. With the explosion of hobbyist users, we've had to make changes to ease the use on our infrastructure.

We made some changes this morning which should resolve the toolkit, though as for your API request, we recommend randomising when you make the call to minimise the chance that you're making API calls at the same time as other users. 

We are currently keeping an eye on our hobbyist traffic and determining potential other solutions.

**Comment by heikone** [comment]
> Looks like it's back up and running again now. The website is populating the graphs and the json is downloadable.
> 
> As for the integration, you will need to reload it but it's started polling again now and bringing figures back.

A reload of the integration did not solve, but a full restart of HA solved this and Solcast is now working.

**Comment by oziee** [comment]
Maybe instead of opening the same issue over and over, users start to learn to search and check closed issues. If you had bothered you would see this question already has been answered.

This isn't a big problem.. a pain, yes. 

creating a new api key WILL NOT solve your problem!! Don't waste your time doing this!

Biggest issue is that the sensors drop out, and this is being addressed.. so when users do get a 429 status the sensors will continue to work

**Comment by Dehumanizer77** [comment]
Maybe if you read my issue carefully, you would notice I did not have a problem with 429. 
I have also tried some API requeats manually and it has worked. Plus the error message I got is not in the closed issues anywhere.

**Comment by oziee** [comment]
@Dehumanizer77 maybe you should understand the error more carefully..

**Comment by oziee** [comment]
> This seems to be a Solcast issue. When using postman to query any and all API endpoints i get
> 
> ```
> {
>     "response_status": {
>         "error_code": "Forbidden",
>         "message": "User does not have active plan for forecast_rooftop_pv_power",
>         "errors": []
>     }
> }
> ```

another user that does not understand what they are doing. Before spurting out issues, make sure you know the issue you are talking about.. there is nothing wrong with Solcast in how you are "testing" as this end point is a PAID product, and unless you have paid for access then you are forbidden to use it..

**Comment by oziee** [comment]
I am personally really getting sick of reading all the self entitles users in here with some of the comments.. 

If you don't like Solcasts "FREE" to use API that allows 10 calls a day, then go find another source and use that. Do not go abusing and spamming Solcast in that they should change their work model so that it suits what you think should be

It's FREE.. and the more that abuse it and start telling them in emails what they should do, they could so easily  just shut down the legacy hobby api. If you are already trying to find ways to continue to allow access without completely shutting it down I see that as a positive, but I also see that if it just becomes to hard to manage and beyond their current and future road map of service that they could just close it down


- do not go renewing your API key.. this is not a fix
- downgrading to and older version of this integration is also not a fix.. 

I am working in the background to change some code to lower the use of server requests be caching some of the data about the sites and adding a little delay when polling the api when users have 2 rooftop sites so that it does not just poll micro seconds apart

The 429 status is annoying.. yes.. would be nicer if the sensors didn't drop out because of it (working on this) as it would not be such a problem
